mysite/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views as myapp_views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flower/<slug:slug>/',myapp_views.detail, name='detail'), #<> are used to capture the url values
    path('tags/<slug:slug>/',myapp_views.tags,name='tags'),
    path('flower/',myapp_views.create, name="create"),
    path('flower/edit/<int:pk>/',myapp_views.edit, name="edit"),
    path('flower/delete/<int:pk>/',myapp_views.delete, name="delete"),
    path('',myapp_views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

myapp/models.py
from distutils.command.upload import upload
from email.policy import default
from unicodedata import category
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Tag(models.Model):
    title = models.CharField(max_length=255, default='')
    slug = models.SlugField(blank=True, default = '')

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Tag, self).save()

class Category(models.Model):
    title = models.CharField(max_length = 255, default = '')

    def __str__(self) -> str:
        return self.title

class Flower(models.Model):
    title = models.CharField(max_length = 255, default = '')
    description = models.TextField(default='')
    slug = models.SlugField(blank = True, default = '')
    category = models.ForeignKey(Category, null=True, on_delete = models.PROTECT)
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(default='', blank=True,upload_to='images')


    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Flower, self).save()

    def get_absolute_url(self):
        return reverse("detail", args=[str(self.slug)])
    

myapp/forms.py
from cProfile import label
from django import forms
from .models import Flower

class MyForm(forms.ModelForm):
    title = forms.CharField(label="Title:", widget=forms.TextInput(attrs={'class':'form-control'}))
    description = forms.CharField(label="Description", widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Flower
        fields = [
            'title',
            'description',                     #represent the field in the form
        ]

base/views.py
from django.shortcuts import render

# Create your views here.

myapp/views.py
from multiprocessing import context
from django.shortcuts import render, get_object_or_404
from myapp.models import Flower
from .forms import MyForm
from django.http import HttpResponseRedirect
from django.contrib import messages

# Create your views here.
def index(request):
    #flowers = Flower.objects.all()
    q = request.GET.get('q', None)
    items = ''

    if q is None or q is '':
        flowers = Flower.objects.all()
    elif q is not None:
        flowers = Flower.objects.filter(title__contains = q)
    return render(request, "myapp/index.html", {'flowers': flowers})

def detail(request, slug=None):               #stores the slug from the url into the variable slug or None if the value is not passed into this parameter
    flower = get_object_or_404(Flower, slug=slug)         #stores the object with the slug into the variable flower if it is found, else it returns error 404
    return render(request, 'myapp/detail.html', {'flower': flower})

def tags(request, slug=None):
    flowers = Flower.objects.filter(tags__slug = slug)
    return render(request, 'myapp/index.html',{'flowers': flowers})


def create(request):
   # context = {}
    if request.method == 'POST':
        form = MyForm(request.POST or None)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    else:
        form = MyForm()

    #context['form'] = form  
    return render(request, 'myapp/create.html',{'form':form})

def edit(request, pk=None):
    flower = get_object_or_404(Flower, pk=pk)
    if request.method == 'POST':
        form = MyForm(request.POST, instance=flower)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = MyForm(instance=flower)

    return render(request, 'myapp/edit.html',{'form':form})

def delete(request, pk=None):
    flower = get_object_or_404(Flower, pk=pk)
    flower.delete()

    return render(request, 'myapp/delete.html',{'flower':flower})

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
        <script src="{% static 'base/js/bootstrap.js'%}"></script>
        <link rel="stylesheet" href="{% static 'base/custome_css/site.css' %}">

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <nav class="navbar navbar-expand-lg navbar-light bg-secondary mb-2">
            <a class="navbar-brand mx-5" href="#">Logo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDrop" arial-controls="navbarDrop" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarDrop">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create' %}">Create Flower</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% comment %} <nav class="navbar navbar-expand navbar-light row bg-secondary mb-2 position-sticky">
            <div class="col-1"></div>
            <div class="col-5">
                <div>
                    <a href="#" class="navbar-brand mx-2">My Logo</a>
                    <div class="collapse navbar-collapse">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Home</a></li>
                            <li class="nav-item"><a href="{% url 'create' %}" class="nav-link">Create Flower</a></li>
                            <li class="nav-item"><a href="#" class="nav-link">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                </div>
            <div class="col-6"></div>
        </nav> {% endcomment %}

        {% comment %} <header class="container-fluid bg-secondary mb-2">
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-5">
                        <ul class="list-unstyled list-inline">
                            <li class="nav-item list-inline-item">
                                <a href="{% url 'index' %}" class="nav-link">
                                Home
                                </a>
                            </li>
                            <li class="nav-item list-inline-item">
                                <a class="nav-link" href="{% url 'create' %}">
                                    Create Flower
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6"></div>
                </div>
        </header> {% endcomment %}
        
        <main role="main" class="container">
            <div id="starter-template">
                {% block content %}{% endblock %}
            </div>
        </main>
        <footer class="footer">
            <div class="container-fluid bg-secondary position-fixed mb-0" style="height: 300px;">
                <div class="row">
                    <span class="text-muted justify-content-center">
                        Base Project for <a href="#">Best Book Tutorial
                    </span>
                </div>
            </div>
        </footer>
        
        <script src="" async defer></script>
    </body>
</html>

myapp/templates/myapp/create.html
{% extends 'base/base.html'%}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col-6">
            {{ form.as_p}}
            <hr class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

myapp/templates/myapp/delete.html
{% extends 'base/base.html'%}
{% block content%}

<h4 class="text-danger">{{flower.title}} has been deleted successfully!</h4>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'base/base.html' %}
{% block content%}
<divv class="jumbotron">
    <div class="container">
        <h1 class="display-3">{{flower.title}}</h1>
        <div class="lead">{{flower.description}}</div>
    </div>
</div>
<a href="{% url 'index' %}">Back</a>
{% endblock %}

myapp/templates/myapp/edit.html
{% extends 'base/base.html'%}
{% block content%}
<h4>Edit the Flower</h4>
<form method="post" action="">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col-6">
           <!--{{ form }}--> 
           {{form.no_field_errors}}

           <div class="form-group">
            {{form.description.errors}}
            {{form.description.label_tag}}
            {{form.description}}
           </div>
           <div class="form-group">
            {{form.title.errors}}
            {{form.title.label_tag}}
            {{form.title}}
           </div>
            <hr class="mb-3">
            <button type="submit" class="btn btn-lg btn-primary btn-block">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
  <div class="row">
      <nav>
          <form method="get" action="/" class="form-inline mt-2 mt-md-0 col-lg-3 col-md-4 col-sm-6 ">
              <div class="input-group">
              <input id="q" name="q" value="{{ request.GET.q }}" class="form-control mr-sm-2" type="text" placeholder="Search..." aria-label="Search">
              <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
              </div>
          </form>
      </nav>
  </div>
</div>

<div class="row my-3">
{% for flower in flowers %}
  <div class="card col-lg-2 col-md-5 mx-1 my-2">
    <img class="card-img my-2" src="{{ flower.image.url }}" alt="image">
    <div class="card-body">
        <h5 class="card-title"><a href="{% url 'detail' flower.slug %}">{{ flower.title }}</a></h5>
        <p class="card-text">{{ flower.description | truncatechars:100 }}</p>
    </div>
    <hr>
    All flowers in the <strong>{{ flower.category }}</strong>category:
    {% for c_flower in flower.category.flower_set.all %}
    <a href="{% url 'detail' c_flower.slug %}">{{ c_flower }}</a>
    {% endfor %}
    <hr>
    Tags:
    {% for tag in flower.tags.all %}
    <a href="{% url 'tags' tag.slug %}">{{ tag }}</a>
    {% endfor %}
    <div class="card-footer text-center">    
        <a href="{% url 'edit' pk=flower.pk %}" class="card-link me-5">Edit</a>
        <a href="{% url 'delete' pk=flower.pk %}" class="card-link">Delete</a>
    </div>
  </div>
{% endfor %}
</div>

{% endblock %}